# Generated by Django 3.0.3 on 2020-02-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
