# Generated by Django 3.0.3 on 2020-02-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200208_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish',
            field=models.CharField(default='draft', max_length=200),
        ),
    ]
