# Generated by Django 3.0.3 on 2020-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200208_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
