# Generated by Django 3.0.3 on 2020-02-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'blank': 'this field in not full, please try again', 'unique': 'this title in not unique,please try again'}, max_length=100, unique=True, verbose_name='Post title'),
        ),
    ]
